notifications:
    email: false

sudo: false
dist: trusty
addons:
    apt:
        packages:
            - tree

branches:
    except:
        - gh-pages

language: java
jdk:
    - oraclejdk8
env:
    global:
        - GRADLE_VERSION='4.4.1'
        - secure: "YSKwjvhh0ANgxY9aZmhZFZhrfbfGMVY9dPMLvHyZk5l2B4fmS/RV8cqx81bHzgII0tBafdAAVWJkzttNJlP0OZJwX8M08GZi2kI/QGqHv528MRcQsBuBhCCCyQMTHn5t1J0U7oW445je41eYAd2zAD7FnZC0+pq8yMJTfDlEy2lUMzpfZJL4YYFEzkXtnePfP3PH5eLo15JL4gPAWa4CE7Sk5MQQbqjaCMQump6uxIpavo5MyxqMeKMQjrKatyrWuQHfJvV94HxK20qfoYmyvEf989Gt2URG1G/+qgEc3i19uQonTP4flH1Ljfw8tPvy74M8tVSoEM/QriQ6eni4cfZUTahh30V2fFU0K/vEQb6/TvZrZ/FFw3ytRVCUEZRWhIRfnJZupkJxgqJY8M59YBtROkn35Bv/IgOB3fxoTSTL17AAfHjg8Ic+aNqRrmfKtGqUHT9WRy+xbNV/6XdXaBi367UJ3wB3ve8XqqRqy8pnMqnoLm+moD1tgoGYBn/KkF2w541MY+t9cB+Q97/ANaphU+CkEFusSCIGiuYp1ZNsqOnqsGaQ9tjCOvJzr7mO4M0rzXXsvtF+1JoFNmYzDy/Drz49G3Q5R75Zg6CAZR5KJOO0g3HlN7GAyaZ31LkjgAwiRyk8vWp7vNxd12I0y9Z4/6MotO2OgFNor1qOimI="
        - secure: "oV3Ty30BcTpM8lUNA8Nuslx2FwH+N3GAKZ1dOwPhJzgjUsrqC159Vwom1xSMfneUfXRhxkZHC26K0nJGXWo6dFdD3vf+3DRgcZPIYOB0RUoiUDDxOG9B/hMKxCpk9LKfxUx02QCV2WZojivemiVTugMXUC9Nh6STxJrcd3LrPIRICUMCHhDYkxUFS0NfWspEJaI/UDi4spRLxxkvCoFSQDdvALqmzHqM4TtoHj24heWgd+ADVSKv7W/AFQOVKhAAWV7aVqIuM8KJJlhx4ETezQWO2Wscw4QP20ZtNkU0QZx1GvnpnElsCczUtyeZrxqSE1uz+LmH8KJMm35PIPkV63nMln4H1UajJdXKZg1vXZJYhzI35ixcx2okQYINQd54SUESOqtRhSEu7NZgREwZYCOQwJW+HvkMcD0yp2ha3VYAAI9Vk+cFSrWaTLDG5e5uJtfpuCZm/ZggIo97LX4qN4pN3aPm01ZHFMVZDRi1Rdbi3TNRD1Ty2FVRMV7BzNAS/DWACXg3XjRVZL7MuZ84TuCITVx6gJgddJcIjHrR9SL2VoRmM7IPXZCgMv/MJAo21MP/DPSndM85m2je1A7fn7WRPkWEPbWgXmzuakae1ZLqnWQsMJgO+T+oPnjxSUnKIG8lB6Rh4W2Rl6UVCo8IcIid8IrNBUVaIasXFxrMbO4="

install:
    - nvm install 8 && nvm use 8

script:
    - npm install
    - npm run build

after_success:
    - ( cd "$HOME" && curl -LO "https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip" )
    - ( cd "$HOME" && unzip -q "gradle-$GRADLE_VERSION-bin.zip" && rm "gradle-$GRADLE_VERSION-bin.zip" )
    - export "PATH=$HOME/gradle-$GRADLE_VERSION/bin:$PATH" && hash -r && gradle --version
    - git --version
    - if [ "$TRAVIS_BRANCH" = "master" ]; then scripts/deploy; fi
