notifications:
    email: false

sudo: required

branches:
    except:
        - gh-pages

language: java
env:
    global:
        - secure: dGdQIlm/318ObAjBEFr6Pw9L0BwbTPk8R1t+uZMg0BiDI8J3u4eWgE1LFwjjCk3k6hG2Qgj7/HNaJm/6uUCRpA9wqIsJdpuc1np8jEWw7x6heb5pZiJp5abQFP3FHQKblaTuXH6t9xspJQF1arHooFarS8sLe1Fb4eLKvbdxRgRY3kUIKRufkKEQO0MVOyvsyeI7edgvV8e7Ee1QUZZFRQl5bx+XTyyDGo+AlY8LGXElVcFlKqCON4k/no4v0yxaLpvNTmz3+Gsqi0WLaS+t0VZfsG40toQAkP6tpNbRETH1lYtTH8FQkDqHFRT/MiipK0hlCw6nPxiYJiNS9QH7l64wlsDi3RBAVv3XNi0ojgGBWY5HWAjiZ+t9/j4OCAb72XEn68Kg66E07MaGlFDr04kKwCtCgAUAVre+ghzC8arKdVFz/SL3lFHxx5/1LVh7GhSY7C2oDSS4uZkcz1zko70/3A/sF0sVR3Vn6bTF1h1CF+nC9kOXojgWQ3ggfmB9vnYGj8p1TbqLxKV0Z3fK9b09PH63QMpCYdujcsI4Ul1KeyEecBWejBwqQBbGnHz1c0qYy6ORu9SdiCTq4f3AwXj5QRPiIrBrSZY/1yPi4I6HATUlilU3fjvAfGnHWSTVLy9aQif2/rSFkNP/85dkz/ksIEbHEwvfjUgF4LoEWX0=
        - secure: rJVkhOnsnI116HoSI/vKzbGegJlIF3fWw6IYpg0e3YCPYPhdTarHF3PIBibJNiSl7jgt5Ky3bzd9QIVhzuytO+2UtO6M3abljJMoIf7ilQYXGYixdMu+jItx7w7NwFI8I3JJmReB/B0pgxVLN+S16rx7/TgedtDSj+4wpa/tmVYgO91NLiOnxvGN9cvHs1DdmNZdZbGJWB+R00IiWhabKgn0dGxyWOgRffGqOmjEyHJYDAVZFINzwKO72pBkcR1rgNgKTLxQTRX+gNKuxbkmNA/g80qBHhzmFu5sCbeV4LH1ERQLUR6lkO6GLpxNMzNIshNSQpviX15he+DT2NqeWgw3H0kQClxRS0w2ndX6Y/Crb5GF559PGqzjNiX8yy6aCir2f/MJA0t8zW5ILJTlJxzsaKgVY+OkWxCi1FX09lu69vv/uNqOfLA3VAIUe5eUpAByZsFt4vgMfIfFJALA1vzvfFch0fzrTAa06gi29luOkYL6A73Thvu8pcyKtsOjelc2qV4d+zGO16K5zmCEjtUGQZwxOkqWcol6zBWwxCM5SJicQc0qQf52V+ESAKAsE/sgGEKavHxGzakAPYN8rXfeIkObarUQtKsT9EUwEEPSC9pb9j4Zg/3EQyNbnIHxGDOntqrr3XZQibiKT6HRcZlGmmB//NNFht232y8U+ug=

install:
    - nvm install 5 && nvm use 5
    - npm install --global npm@3

script:
    - npm install
    - npm run build

after_success:
    - sudo apt-get -y purge git
    - sudo add-apt-repository -y ppa:git-core/ppa
    - sudo apt-get update
    - sudo apt-get -y install git
    - git --version
    - scripts/deploy
