notifications:
    email: false

branches:
    except:
        - gh-pages

language: java

install:
    - nvm install 5 && nvm use 5
    - npm install --global npm@3

script:
    - npm install
    - npm run build
